Repository Iroff1/support-lab-backend, pull requests merged in 2025-05, with the labels that each got.

#2 프로젝트 초기 설정
  .database/local/docker-compose.yml
  .github/issue_template.md
  .github/pull_request_template.md
  build.gradle
  checkstyle/naver-checkstyle-rules.xml
  checkstyle/naver-checkstyle-suppressions.xml
  checkstyle/naver-intellij-formatter.xml
  src/main/java/com/iroff/supportlab/SupportLabBackendApplication.java
  src/main/java/com/iroff/supportlab/application/user/dto/SignUpUserRequest.java
  src/main/java/com/iroff/supportlab/application/user/dto/SignUpUserResponse.java
  src/main/java/com/iroff/supportlab/application/user/service/SignUpUserInteractor.java
  src/main/java/com/iroff/supportlab/domain/global/model/BaseTime.java
  src/main/java/com/iroff/supportlab/domain/user/model/Role.java
  src/main/java/com/iroff/supportlab/domain/user/model/User.java
  src/main/java/com/iroff/supportlab/domain/user/port/in/SignUpUserUseCase.java
  src/main/java/com/iroff/supportlab/domain/user/port/out/UserRepository.java
  src/main/java/com/iroff/supportlab/presentation/global/out/persistence/BaseTimeEntity.java
  src/main/java/com/iroff/supportlab/presentation/user/in/web/UserController.java
  src/main/java/com/iroff/supportlab/presentation/user/out/persistence/UserEntity.java
  src/main/java/com/iroff/supportlab/presentation/user/out/persistence/UserJpaRepository.java
  src/main/java/com/iroff/supportlab/presentation/user/out/persistence/UserRepositoryImpl.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/com/iroff/supportlab/SupportLabBackendApplicationTests.java
Labels: chore, refactor

#3 Develop 브랜치 Main 병합
  .database/local/docker-compose.yml
  .github/issue_template.md
  .github/pull_request_template.md
  build.gradle
  checkstyle/naver-checkstyle-rules.xml
  checkstyle/naver-checkstyle-suppressions.xml
  checkstyle/naver-intellij-formatter.xml
  src/main/java/com/iroff/supportlab/SupportLabBackendApplication.java
  src/main/java/com/iroff/supportlab/application/user/dto/SignUpUserRequest.java
  src/main/java/com/iroff/supportlab/application/user/dto/SignUpUserResponse.java
  src/main/java/com/iroff/supportlab/application/user/service/SignUpUserInteractor.java
  src/main/java/com/iroff/supportlab/domain/global/model/BaseTime.java
  src/main/java/com/iroff/supportlab/domain/user/model/Role.java
  src/main/java/com/iroff/supportlab/domain/user/model/User.java
  src/main/java/com/iroff/supportlab/domain/user/port/in/SignUpUserUseCase.java
  src/main/java/com/iroff/supportlab/domain/user/port/out/UserRepository.java
  src/main/java/com/iroff/supportlab/presentation/global/out/persistence/BaseTimeEntity.java
  src/main/java/com/iroff/supportlab/presentation/user/in/web/UserController.java
  src/main/java/com/iroff/supportlab/presentation/user/out/persistence/UserEntity.java
  src/main/java/com/iroff/supportlab/presentation/user/out/persistence/UserJpaRepository.java
  src/main/java/com/iroff/supportlab/presentation/user/out/persistence/UserRepositoryImpl.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/com/iroff/supportlab/SupportLabBackendApplicationTests.java
Labels: chore, refactor

#5 chore: local yml 파일 삭제 및 .gitignore 추가
  .gitignore
  src/main/resources/application-local.yml
Labels: chore

#6 [BE] local properties 파일 .gitignore에 추가
  .gitignore
  src/main/resources/application-local.yml
Labels: chore

#9 [BE] Entity에 @Getter 어노테이션 추가
  src/main/java/com/iroff/supportlab/presentation/global/out/persistence/BaseTimeEntity.java
  src/main/java/com/iroff/supportlab/presentation/user/out/persistence/UserEntity.java
Labels: fix

#11 [BE] security 설정
  build.gradle
  src/main/java/com/iroff/supportlab/domain/user/port/out/UserRepository.java
  src/main/java/com/iroff/supportlab/presentation/config/global/security/CustomUserDetails.java
  src/main/java/com/iroff/supportlab/presentation/config/global/security/CustomUserDetailsService.java
  src/main/java/com/iroff/supportlab/presentation/config/global/security/SecurityConfig.java
  src/main/java/com/iroff/supportlab/presentation/user/out/persistence/UserJpaRepository.java
  src/main/java/com/iroff/supportlab/presentation/user/out/persistence/UserRepositoryImpl.java
Labels: feat

#12 [BE] 커스텀 예외 처리 로직 구현
  src/main/java/com/iroff/supportlab/application/user/service/SignUpUserInteractor.java
  src/main/java/com/iroff/supportlab/domain/common/model/BaseTime.java
  src/main/java/com/iroff/supportlab/domain/common/port/in/Validator.java
  src/main/java/com/iroff/supportlab/domain/common/port/in/exception/DomainException.java
  src/main/java/com/iroff/supportlab/domain/common/port/in/exception/ErrorInfo.java
  src/main/java/com/iroff/supportlab/domain/user/model/User.java
  src/main/java/com/iroff/supportlab/domain/user/port/in/SignUpUserUseCase.java
  src/main/java/com/iroff/supportlab/domain/user/port/in/exception/UserError.java
  src/main/java/com/iroff/supportlab/presentation/common/in/web/exception/APIException.java
  src/main/java/com/iroff/supportlab/presentation/common/in/web/exception/ErrorResponse.java
  src/main/java/com/iroff/supportlab/presentation/common/in/web/exception/ErrorStatus.java
  src/main/java/com/iroff/supportlab/presentation/common/in/web/exception/GlobalExceptionHandler.java
  src/main/java/com/iroff/supportlab/presentation/common/out/persistence/BaseTimeEntity.java
  src/main/java/com/iroff/supportlab/presentation/user/in/web/UserController.java
  src/main/java/com/iroff/supportlab/presentation/user/in/web/exception/UserErrorStatus.java
  src/main/java/com/iroff/supportlab/presentation/user/out/persistence/UserEntity.java
  src/main/resources/application-dev.yml
Labels: feat, chore

#19 main -> develop 병합
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/issue.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/issue_template.md
  src/main/java/com/iroff/supportlab/application/user/service/SignUpUserInteractor.java
  src/main/java/com/iroff/supportlab/domain/common/model/BaseTime.java
  src/main/java/com/iroff/supportlab/domain/common/port/in/Validator.java
  src/main/java/com/iroff/supportlab/domain/common/port/in/exception/DomainException.java
  src/main/java/com/iroff/supportlab/domain/common/port/in/exception/ErrorInfo.java
  src/main/java/com/iroff/supportlab/domain/user/model/User.java
  src/main/java/com/iroff/supportlab/domain/user/port/in/SignUpUserUseCase.java
  src/main/java/com/iroff/supportlab/domain/user/port/in/exception/UserError.java
  src/main/java/com/iroff/supportlab/presentation/common/in/web/exception/APIException.java
  src/main/java/com/iroff/supportlab/presentation/common/in/web/exception/ErrorResponse.java
  src/main/java/com/iroff/supportlab/presentation/common/in/web/exception/ErrorStatus.java
  src/main/java/com/iroff/supportlab/presentation/common/in/web/exception/GlobalExceptionHandler.java
  src/main/java/com/iroff/supportlab/presentation/common/out/persistence/BaseTimeEntity.java
  src/main/java/com/iroff/supportlab/presentation/user/in/web/UserController.java
  src/main/java/com/iroff/supportlab/presentation/user/in/web/exception/UserErrorStatus.java
  src/main/java/com/iroff/supportlab/presentation/user/out/persistence/UserEntity.java
  src/main/resources/application-dev.yml
Labels: help wanted

#21 [BE] 회원가입 서비스 구현
  build.gradle
  src/main/java/com/iroff/supportlab/adapter/common/in/web/exception/GlobalExceptionHandler.java
  src/main/java/com/iroff/supportlab/adapter/config/global/security/SecurityConfig.java
  src/main/java/com/iroff/supportlab/adapter/user/in/web/UserController.java
  src/main/java/com/iroff/supportlab/adapter/user/in/web/exception/UserErrorStatus.java
  src/main/java/com/iroff/supportlab/adapter/user/out/persistence/UserEntity.java
  src/main/java/com/iroff/supportlab/adapter/user/out/persistence/UserJpaRepository.java
  src/main/java/com/iroff/supportlab/adapter/user/out/persistence/UserRepositoryImpl.java
  src/main/java/com/iroff/supportlab/application/user/dto/SignUpUserRequest.java
  src/main/java/com/iroff/supportlab/application/user/dto/SignUpUserResponse.java
  src/main/java/com/iroff/supportlab/application/user/service/SignUpUserInteractor.java
  src/main/java/com/iroff/supportlab/domain/user/port/in/exception/UserError.java
  src/main/java/com/iroff/supportlab/domain/user/port/out/UserRepository.java
Labels: feat

#25 [BE] 입력 검증 예외처리 중복빈에 따른 수정
  src/main/java/com/iroff/supportlab/adapter/common/in/web/exception/GlobalExceptionHandler.java
Labels: fix

#28 [BE] 회원가입 서비스 추가 구현
  src/main/java/com/iroff/supportlab/adapter/auth/in/web/exception/AuthErrorStatus.java
  src/main/java/com/iroff/supportlab/adapter/common/in/web/exception/GlobalExceptionHandler.java
  src/main/java/com/iroff/supportlab/adapter/user/in/web/exception/UserErrorStatus.java
  src/main/java/com/iroff/supportlab/adapter/user/out/persistence/UserJpaRepository.java
  src/main/java/com/iroff/supportlab/adapter/user/out/persistence/UserRepositoryImpl.java
  src/main/java/com/iroff/supportlab/application/common/dto/ResponseDTO.java
  src/main/java/com/iroff/supportlab/application/common/dto/vo/ResponseCode.java
  src/main/java/com/iroff/supportlab/application/user/dto/SignUpUserRequest.java
  src/main/java/com/iroff/supportlab/application/user/service/SignUpUserInteractor.java
  src/main/java/com/iroff/supportlab/domain/auth/port/in/exception/AuthError.java
  src/main/java/com/iroff/supportlab/domain/user/port/in/exception/UserError.java
  src/main/java/com/iroff/supportlab/domain/user/port/out/UserRepository.java
Labels: fix, feat, refactor

#27 [BE] 로그인(JWT) 서비스 구현
  build.gradle
  src/main/java/com/iroff/supportlab/adapter/auth/in/web/AuthController.java
  src/main/java/com/iroff/supportlab/adapter/auth/in/web/exception/AuthErrorStatus.java
  src/main/java/com/iroff/supportlab/adapter/auth/in/web/exception/AuthExceptionHandler.java
  src/main/java/com/iroff/supportlab/adapter/config/global/security/JwtAuthenticationEntryPoint.java
  src/main/java/com/iroff/supportlab/adapter/config/global/security/JwtAuthenticationFilter.java
  src/main/java/com/iroff/supportlab/adapter/config/global/security/JwtTokenProvider.java
  src/main/java/com/iroff/supportlab/adapter/config/global/security/SecurityConfig.java
  src/main/java/com/iroff/supportlab/application/auth/dto/LoginRequest.java
  src/main/java/com/iroff/supportlab/application/auth/dto/LoginResponse.java
  src/main/java/com/iroff/supportlab/application/auth/service/LoginInteractor.java
  src/main/java/com/iroff/supportlab/domain/auth/exception/AuthException.java
  src/main/java/com/iroff/supportlab/domain/auth/port/in/LoginUseCase.java
  src/main/java/com/iroff/supportlab/domain/auth/port/in/exception/AuthError.java
  src/main/resources/application.yml
Labels: feat
